#!/bin/bash

# Update package lists
apt-get update

# Install vim
apt-get install -y vim

# Set CUDA_HOME environment variable
export CUDA_HOME=/usr/local/cuda-11.8

export HUGGING_FACE_HUB_TOKEN="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"

# Install Python packages
pip install -U git+https://github.com/huggingface/transformers.git
pip install sentencepiece
pip install ninja
pip install flash-attn --no-build-isolation
pip install git+https://github.com/HazyResearch/flash-attention.git#subdirectory=csrc/rotary

# Install additional requirements from requirements.txt
pip install -r requirements.txt
